---
language: node_js

node_js:
  - 10

env:
  global:
  - BLOG_REPO_NAME=liuyanjie.github.io
  - BLOG_REPO=https://github.com/liuyanjie/liuyanjie.github.io.git

before_install:
  # - export TZ='Asia/Shanghai'
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - git config --global user.name  liuyanie-ci-bot
  - git config --global user.email liuyanie-ci-bot@mail.com

script:
  - git clone ${BLOG_REPO}
  - git clone -b master ${BLOG_REPO} ${BLOG_REPO_NAME}/.deploy_git
  - cd ${BLOG_REPO_NAME}
  - git submodule init
  - git submodule update
  - yarn install
  - rm -rf source/_post/*
  - npx hexo clean
  - npx hexo-post -c .. -o .
  - npx hexo d -g
